In [53]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import neighbors, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [54]:
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
print('Số các loại: %d' %len(set(iris_y)))
print('Số điểm dữ liệu: %d' %len(iris_y))

Số các loại: 3
Số điểm dữ liệu: 150


In [55]:
X0 = iris_X[iris_y == 0,:]
print('Dữ liệu loại 0: \n', X0[:5,:])

Dữ liệu loại 0: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [56]:
X1 = iris_X[iris_y == 1,:]
print('Dữ liệu loại 1: \n', X1[:5,:])

Dữ liệu loại 1: 
 [[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]


In [57]:
X2 = iris_X[iris_y == 2,:]
print('Dữ liệu loại 2: \n', X2[:5,:])

Dữ liệu loại 2: 
 [[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]]


In [58]:
X_train, X_test, y_train, y_test = train_test_split(iris_X, iris_y, test_size=50) #chia dữ liệu thành 2 phần: 100 dữ liệu train, 50 dữ liệu test
print('Số dữ liệu train: %d' %len(y_train))
print('Số dữ liệu test: %d' %len(y_test))

Số dữ liệu train: 100
Số dữ liệu test: 50


In [59]:
clf = neighbors.KNeighborsClassifier(n_neighbors = 1, p = 2) #p = 2 là khoảng cách Euclid
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print('Kết quả dự đoán: \n', y_pred)
print('Kết quả thực: \n', y_test)

Kết quả dự đoán: 
 [2 2 0 1 0 0 0 0 1 0 0 1 2 2 1 2 1 2 1 0 0 2 2 0 2 1 2 1 1 2 0 1 2 0 2 0 0
 2 1 2 1 1 0 1 2 1 0 2 0 0]
Kết quả thực: 
 [2 2 0 1 0 0 0 0 1 0 0 1 2 2 1 2 1 2 1 0 0 2 2 0 2 1 2 1 1 2 0 1 2 0 2 0 0
 2 1 2 1 1 0 1 2 1 0 2 0 0]


In [60]:
print('Độ chính xác: %.2f %%' %(100*accuracy_score(y_test, y_pred)))

Độ chính xác: 100.00 %


In [61]:
clf = neighbors.KNeighborsClassifier(n_neighbors = 10, p = 2)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print('Kết quả dự đoán: \n', y_pred)
print('Kết quả thực: \n', y_test)

Kết quả dự đoán: 
 [2 2 0 1 0 0 0 0 1 0 0 1 2 2 1 2 1 2 1 0 0 2 2 0 2 1 2 1 1 2 0 1 2 0 2 0 0
 2 1 2 1 1 0 1 2 1 0 2 0 0]
Kết quả thực: 
 [2 2 0 1 0 0 0 0 1 0 0 1 2 2 1 2 1 2 1 0 0 2 2 0 2 1 2 1 1 2 0 1 2 0 2 0 0
 2 1 2 1 1 0 1 2 1 0 2 0 0]


In [62]:
print('Độ chính xác: %.2f %%' %(100*accuracy_score(y_test, y_pred)))

Độ chính xác: 100.00 %


In [63]:
clf = neighbors.KNeighborsClassifier(n_neighbors = 10, p = 2, weights = 'distance') #weights = 'distance' là trọng số của các điểm dữ liệu
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print('Kết quả dự đoán: \n', y_pred)
print('Kết quả thực: \n', y_test)

Kết quả dự đoán: 
 [2 2 0 1 0 0 0 0 1 0 0 1 2 2 1 2 1 2 1 0 0 2 2 0 2 1 2 1 1 2 0 1 2 0 2 0 0
 2 1 2 1 1 0 1 2 1 0 2 0 0]
Kết quả thực: 
 [2 2 0 1 0 0 0 0 1 0 0 1 2 2 1 2 1 2 1 0 0 2 2 0 2 1 2 1 1 2 0 1 2 0 2 0 0
 2 1 2 1 1 0 1 2 1 0 2 0 0]


In [64]:
print('Độ chính xác: %.2f %%' %(100*accuracy_score(y_test, y_pred)))

Độ chính xác: 100.00 %


In [65]:
def myweight(distances):
    sigma2 = .5
    return np.exp(-distances**2/sigma2)
clf = neighbors.KNeighborsClassifier(n_neighbors = 10, p = 2, weights = myweight)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print('Kết quả dự đoán: \n', y_pred)
print('Kết quả thực: \n', y_test)

Kết quả dự đoán: 
 [2 2 0 1 0 0 0 0 1 0 0 1 2 2 1 2 1 2 1 0 0 2 2 0 2 1 2 1 1 2 0 1 2 0 2 0 0
 2 1 2 1 1 0 1 2 1 0 2 0 0]
Kết quả thực: 
 [2 2 0 1 0 0 0 0 1 0 0 1 2 2 1 2 1 2 1 0 0 2 2 0 2 1 2 1 1 2 0 1 2 0 2 0 0
 2 1 2 1 1 0 1 2 1 0 2 0 0]


In [66]:
print('Độ chính xác: %.2f %%' %(100*accuracy_score(y_test, y_pred)))

Độ chính xác: 100.00 %
